# -------------------------
# Firewall and Security Group Outputs
# -------------------------

output "firewall_rules" {
  value       = local.firewall_rules
  description = "This shows the firewall rules generated by merging common rules with game-specific rules."
  sensitive = true
}

output "games" {
  value       = local.games
  description = "List of all the games extracted from the games.yaml file."
}

output "security_group_ids" {
  value       = { for game, mod in module.server_firewall : game => mod.security_group_id }
  description = "Security group IDs for each game's firewall."
  sensitive = true
}


# -------------------------
# VPC and Subnet Outputs
# -------------------------

output "vpc_id" {
  value       = module.terraplay_vpc.vpc_id
  description = "The ID of the VPC created for the game servers and related infrastructure."
  sensitive = true
}

output "subnets" {
  value = {
    public_subnets  = module.terraplay_vpc.public_subnets.public
    private_subnets = module.terraplay_vpc.private_subnets.private
  }
  description = "Lists the public and private subnets created in the VPC. This can be used to configure EC2 instances or other resources."
  sensitive = true
}


# -------------------------
# Session Database Outputs
# -------------------------

output "sessions_database" {
  value       = module.session_table.dynamodb_table_name
  description = "The name of the DynamoDB table used for tracking game sessions and storing session-related data."
  sensitive = true
}


# -------------------------
# SSH Key Pair Output
# -------------------------

output "aws_key_name" {
  description = "The AWS key name used for SSH"
  value       = module.ssh_key.aws_key_name
  sensitive = true
}


# -------------------------
# EC2 Bot Server Outputs
# -------------------------

output "bot_server_info" {
  value = {
    public_ip   = module.bot_server.public_ip
    instance_id = module.bot_server.instance_id
    info        = module.bot_server.*
  }
  description = "The public IP, instance ID, and additional info for the EC2 bot server."
  sensitive = true
}

# -------------------------
# ECR Repository Outputs
# -------------------------

output "ecr_repository_url" {
  value       = module.global_ecr_repository.ecr_repository_uri
  description = "The URL of the ECR repository for storing Docker images for the bot server."
  sensitive = true
}


# -------------------------
# S3 Bucket Outputs
# -------------------------

output "global_bucket_name" {
  value       = module.global_bucket.bucket_name
  description = "The name of the S3 bucket used for storing global game data backups."
  sensitive = true
}

output "global_bucket_id" {
  value       = module.global_bucket.bucket_id
  description = "The ID of the S3 bucket used for storing global game data backups."
  sensitive = true
}

# -------------------------
# S3 Bucket Outputs
# -------------------------

output "secrets_manager_name" {
  value       = aws_secretsmanager_secret.this.name
  description = "This is the name of Secrets Manager for storing the environment variables"
  sensitive = true
}
