# -------------------------
# Firewall and Security Group Outputs
# -------------------------

# Outputs the merged firewall rules, combining common ingress/egress rules with game-specific rules.
output "firewall_rules" {
  value       = local.firewall_rules
  description = "This shows the firewall rules generated by merging common rules with game-specific rules."
}

# Outputs a list of all the games that were parsed from the games.yaml file.
output "games" {
  value       = local.games
  description = "List of all the games extracted from the games.yaml file."
}

# Outputs the security group IDs for each game's firewall. This maps the game name to the security group created for it.
output "security_group_ids" {
  value       = { for game, mod in module.server_firewall : game => mod.security_group_id }
  description = "Security group IDs for each game's firewall."
}


# -------------------------
# VPC and Subnet Outputs
# -------------------------

# Outputs the ID of the VPC that was created by the terraplay_vpc module.
output "vpc_id" {
  value       = module.terraplay_vpc.vpc_id
  description = "The ID of the VPC created for the game servers and related infrastructure."
}

# Outputs the public and private subnets created within the VPC.
output "subnets" {
  value = {
    public_subnets  = module.terraplay_vpc.public_subnets.public
    private_subnets = module.terraplay_vpc.private_subnets.private
  }
  description = "Lists the public and private subnets created in the VPC. This can be used to configure EC2 instances or other resources."
}


# -------------------------
# Session Database Outputs
# -------------------------

# Outputs the name of the DynamoDB table created for session tracking.
output "sessions_database" {
  value       = module.session_table.dynamodb_table_name
  description = "The name of the DynamoDB table used for tracking game sessions and storing session-related data."
}



output "aws_key_name" {
  description = "The AWS key name used for SSH"
  value       = module.ssh_key.aws_key_name
}


output "bot_server_info" {
  value = {
    public_ip   = module.bot_server.public_ip
    instance_id = module.bot_server.instance_id
    info= module.bot_server.*
  }
}


output "amzon_linux_2" {
  value = data.aws_ami.amazon_linux.*
}


