name: Build and Push Docker to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make build script executable
        run: chmod +x ./scripts/build.ecr.sh

      - name: Run build and push script
        run: ./scripts/build.ecr.sh
        env:
          AWS_REGION: ${{ secrets.AWS_REGION}}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
