name: Build and Push Docker to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Image Tag with Date-Time
        id: set_tag
        run: echo "::set-output name=image_tag::$(date +'%Y%m%d-%H%M')"

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build and Tag Docker Image
        run: |
          IMAGE_TAG=${{ steps.set_tag.outputs.image_tag }}
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/nimbus-bot:$IMAGE_TAG .
          docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/nimbus-bot:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/nimbus-bot:latest

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG=${{ steps.set_tag.outputs.image_tag }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/nimbus-bot:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/nimbus-bot:latest

      - name: Trigger Repository Dispatch to Deploy Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_TOKEN }}  
          event-type: deploy-trigger
          client-payload: '{"image_tag": "${{ steps.set_tag.outputs.image_tag }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
