name: Deploy Bot to EC2

on:
  repository_dispatch:
    types: [deploy-trigger]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      
      - name: Set debug flag to true
        run: echo "ACTION_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Encode the secrets
        run: |
          echo "${{ secrets.EC2_HOST }}" | base64
          echo "Base64-encoded secret: $(echo "${{ secrets.EC2_HOST }}" | base64)"

      - name: Print environment variables (for debugging)
        run: |
          echo "EC2_HOST=${{ secrets.EC2_HOST }}"
          echo "EC2_USER=${{ secrets.EC2_USER }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}"
          echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}"
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}"
          echo "DISCORD_CHANNEL_ID=${{ secrets.DISCORD_CHANNEL_ID }}"
          echo "REPO_TOKEN=${{ secrets.REPO_TOKEN }}"
          echo "ACTIONS_WEBHOOK_SECRET=${{ secrets.ACTIONS_WEBHOOK_SECRET }}"
          echo "DYNAMO_TABLE=${{ secrets.DYNAMO_TABLE }}"
          echo "APP_ENV=${{ secrets.APP_ENV }}"
          echo "EC2_SSH_KEY=${{ secrets.EC2_SSH_KEY }}"

      - name: Deploy Bot to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
          ACTIONS_WEBHOOK_SECRET: ${{ secrets.ACTIONS_WEBHOOK_SECRET }}
          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}
          APP_ENV: ${{ secrets.APP_ENV }}
        run: |
          chmod +x ./scripts/deploy-bot.sh
          ./scripts/deploy-bot.sh
