name: Start Game Server

on:
  workflow_dispatch:
    inputs:
      game: 
        description: "What is the context of the infra? (e.g. global or minetest or warzone2100)"
        required: true
        default: 'global'
        type: string
      user_id:
        description: "What is the user_id of the infra?"
        required: true
        type: string
      run_id:
        description: "To track the action workflow dispatch"
        required: true
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup Infrastructure
        run: |
          chmod +x ./scripts/start.sh
          ./scripts/start.sh ${{ github.event.inputs.game }} ${{ github.event.inputs.user_id }}
        working-directory: ./infra
      
      - name: Output Server IP
        run: |
          echo "server_ip=$(terraform output -raw server_ip)" >> $GITHUB_ENV
          echo "game=${{ github.event.inputs.game }}" >> $GITHUB_ENV
          echo "user_id=${{ github.event.inputs.user_id }}" >> $GITHUB_ENV
          echo "run_id=${{ github.event.inputs.run_id }}" >> $GITHUB_ENV

      - name: Set outputs for inputs
        run: |
          echo "::set-output name=game::${{ github.event.inputs.game }}"
          echo "::set-output name=user_id::${{ github.event.inputs.user_id }}"
          echo "::set-output name=run_id::${{ github.event.inputs.run_id }}"
          echo "::set-output name=server_ip::${{ env.server_ip }}"