name: Start Game Server

on:
    workflow_dispatch:
        inputs:
            game: 
                description: "What is the context of the infra? (e.g. global or minetest or warzone2100)"
                required: true
                default: 'global'
                type: string
            user_id:
                description: "What is the user_id of the infra?"
                required: true
                type: string
            
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v2
            
            - name: Setup Infrastructure
              run: |
                chmod +x ./scripts/start.sh
                ./scripts/start.sh ${{ github.event.inputs.game }} ${{ github.event.inputs.user_id }}
              working-directory: ./infra