name: Stop Game Server

on:
    workflow_dispatch:
        inputs:
            workspace: 
                description: "What is the context of the infra? (e.g. global or minetest or warzone2100)"
                required: true
                type: string
            run_id:
              description: "What is the run_id?"
              required: true
              type: string
permissions:
    id-token: write
    contents: read
    pull-requests: write
env:
    TF_LOG: INFO
    AWS_REGION: ${{ secrets.AWS_REGION }}
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    TF_BACKEND_STATE_STORAGE: ${{ secrets.TF_BACKEND_STATE_STORAGE }}
    TF_BACKEND_KEY: ${{ secrets.TF_BACKEND_KEY }}
    TF_BACKEND_LOCK_TABLE: ${{ secrets.TF_BACKEND_LOCK_TABLE }}
    GLOBAL_WORKSPACE_NAME: ${{secrets.GLOBAL_WORKSPACE_NAME}}

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: ./infra
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
  
          - name: Configure AWS credentials from AWS account
            uses: aws-actions/configure-aws-credentials@v1
            with:
              role-to-assume: ${{ secrets.AWS_ROLE }}
              aws-region: ${{ secrets.AWS_REGION }}
              role-session-name: GitHub-OIDC-TERRAFORM
              
          - name: Terraform init
            id: init
            run: terraform init -backend-config="bucket=${TF_BACKEND_STATE_STORAGE}" -backend-config="key=${TF_BACKEND_KEY}" -backend-config="dynamodb_table=${TF_BACKEND_LOCK_TABLE}" -backend-config="region=${AWS_REGION}"   
            
          - name: Setup Infrastructure
            run: |
              chmod +x ./scripts/kill.sh
              ./scripts/kill.sh ${{ github.event.inputs.workspace }}
            working-directory: ./infra
              
          - name: Output Inputs
            run: echo "${{ toJSON(github.event.inputs) }}"